### PR TITLE
Remove doubly nested inner classes

### LINKED ISSUE #551: Exception thrown if k8s namer encounters unexpected end of stream
`jpe.getMessage` throws `java.lang.InternalError: Malformed class name` because `java.lang.Class.getSimpleName` is called on a doubly-nested inner class, which hits this scala bug: https://issues.scala-lang.org/browse/SI-2034 

<details>
I 0720 16:01:08.383 THREAD21 TraceId:a3a2217ce6f62184: Resolver[inet] = com.twitter.finagle.InetResolver(com.twitter.finagle.InetResolver@77ce885a)
I 0720 16:01:08.384 THREAD21 TraceId:a3a2217ce6f62184: Resolver[fail] = com.twitter.finagle.FailResolver$(com.twitter.finagle.FailResolver$@680b5192)
I 0720 16:01:08.384 THREAD21 TraceId:a3a2217ce6f62184: Resolver[flag] = com.twitter.server.FlagResolver(com.twitter.server.FlagResolver@61446a6e)
I 0720 16:01:08.384 THREAD21 TraceId:a3a2217ce6f62184: Resolver[fixedinet] = com.twitter.finagle.FixedInetResolver(com.twitter.finagle.FixedInetResolver@3986081d)
I 0720 16:01:08.384 THREAD21 TraceId:a3a2217ce6f62184: Resolver[neg] = com.twitter.finagle.NegResolver$(com.twitter.finagle.NegResolver$@628e2e2b)
I 0720 16:01:08.384 THREAD21 TraceId:a3a2217ce6f62184: Resolver[nil] = com.twitter.finagle.NilResolver$(com.twitter.finagle.NilResolver$@6b8498e0)
I 0720 16:01:08.385 THREAD21 TraceId:a3a2217ce6f62184: Resolver[zk] = com.twitter.finagle.zookeeper.ZkResolver(com.twitter.finagle.zookeeper.ZkResolver@7228ef1b)
I 0720 16:01:08.385 THREAD21 TraceId:a3a2217ce6f62184: Resolver[zk2] = com.twitter.finagle.serverset2.Zk2Resolver(com.twitter.finagle.serverset2.Zk2Resolver@3da42a26)
VM error: Malformed class name
E 0720 16:01:12.446 THREAD22: VM error
java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Class.java:1330)
    at com.fasterxml.jackson.databind.JsonMappingException$Reference.toString(JsonMappingException.java:108)
    at com.fasterxml.jackson.databind.JsonMappingException._appendPathDesc(JsonMappingException.java:342)
    at com.fasterxml.jackson.databind.JsonMappingException.getPathReference(JsonMappingException.java:245)
    at com.fasterxml.jackson.databind.JsonMappingException._buildMessage(JsonMappingException.java:318)
    at com.fasterxml.jackson.databind.JsonMappingException.getMessage(JsonMappingException.java:299)
    at io.buoyant.k8s.Json$Incomplete$.unapply(Json.scala:41)
    at io.buoyant.k8s.Json$$anonfun$readChunked$1.apply(Json.scala:87)
    at io.buoyant.k8s.Json$$anonfun$readChunked$1.apply(Json.scala:59)
    at io.buoyant.k8s.Json$.parse(Json.scala:50)
    at io.buoyant.k8s.Json$.readChunked(Json.scala:59)
    at io.buoyant.k8s.Json$$anonfun$io$buoyant$k8s$Json$$chunks$1$3.apply(Json.scala:122)
    at io.buoyant.k8s.Json$$anonfun$io$buoyant$k8s$Json$$chunks$1$3.apply(Json.scala:107)
    at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$3.apply(Future.scala:1148)
    at com.twitter.util.Try$.apply(Try.scala:13)
    at com.twitter.util.Future$.apply(Future.scala:165)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1148)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1147)
    at com.twitter.util.ConstFuture$$anon$6.run(Future.scala:1481)
    at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:201)
    at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:159)
    at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:239)
    at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:107)
    at com.twitter.util.Promise.runq(Promise.scala:405)
    at com.twitter.util.Promise.updateIfEmpty(Promise.scala:796)
    at com.twitter.util.Promise.update(Promise.scala:770)
    at com.twitter.util.Promise.setValue(Promise.scala:746)
    at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
    at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
    at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
    at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
    at java.lang.Thread.run(Thread.java:745)
java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Class.java:1330)
    at com.fasterxml.jackson.databind.JsonMappingException$Reference.toString(JsonMappingException.java:108)
    at com.fasterxml.jackson.databind.JsonMappingException._appendPathDesc(JsonMappingException.java:342)
    at com.fasterxml.jackson.databind.JsonMappingException.getPathReference(JsonMappingException.java:245)
    at com.fasterxml.jackson.databind.JsonMappingException._buildMessage(JsonMappingException.java:318)
    at com.fasterxml.jackson.databind.JsonMappingException.getMessage(JsonMappingException.java:299)
    at io.buoyant.k8s.Json$Incomplete$.unapply(Json.scala:41)
    at io.buoyant.k8s.Json$$anonfun$readChunked$1.apply(Json.scala:87)
    at io.buoyant.k8s.Json$$anonfun$readChunked$1.apply(Json.scala:59)
    at io.buoyant.k8s.Json$.parse(Json.scala:50)
    at io.buoyant.k8s.Json$.readChunked(Json.scala:59)
    at io.buoyant.k8s.Json$$anonfun$io$buoyant$k8s$Json$$chunks$1$3.apply(Json.scala:122)
    at io.buoyant.k8s.Json$$anonfun$io$buoyant$k8s$Json$$chunks$1$3.apply(Json.scala:107)
    at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$3.apply(Future.scala:1148)
    at com.twitter.util.Try$.apply(Try.scala:13)
    at com.twitter.util.Future$.apply(Future.scala:165)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1148)
    at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1147)
    at com.twitter.util.ConstFuture$$anon$6.run(Future.scala:1481)
    at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:201)
    at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:159)
    at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:239)
    at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:107)
    at com.twitter.util.Promise.runq(Promise.scala:405)
    at com.twitter.util.Promise.updateIfEmpty(Promise.scala:796)
    at com.twitter.util.Promise.update(Promise.scala:770)
    at com.twitter.util.Promise.setValue(Promise.scala:746)
    at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:120)
    at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
    at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.handler.codec.http.HttpClientCodec.handleUpstream(HttpClientCodec.java:92)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
    at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:68)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
    at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:32)
    at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.ja
</details>

### PR DESCRIPTION
**Pull request by adleong**
Fixes #551 

Avoid https://issues.scala-lang.org/browse/SI-2034 by not using doubly-nested inner classes.

### CODE REVIEW

File: k8s/src/main/scala/io/buoyant/k8s/v1.scala [hunk 1]
```diff
@@ -15,33 +15,31 @@ package object v1 {
...
+    `object`: Endpoints
+  ) extends EndpointsWatch with Watch.Modified[Endpoints]
+
+  case class Deleted(
+    `object`: Endpoints
+  ) extends EndpointsWatch with Watch.Deleted[Endpoints]
+
+  case class Error(
+    @JsonProperty(value = "object") status: Status
+  ) extends EndpointsWatch with Watch.Error[Endpoints]
```
Comment (gtcampbell) [inline k8s/src/main/scala/io/buoyant/k8s/v1.scala]: for my education: I had assumed we would handle this by making `v1` a package rather than a package object, thus avoiding the extra level of object nesting for everything inside it. Would that also have worked around this bug, or am I missing something?

Comment (adleong) [inline k8s/src/main/scala/io/buoyant/k8s/v1.scala]: `v1` contains `implicit object EndpointsDescriptor` and implicit classes can't live in packages.  I tried splitting this up so that some things went into the package and others into the package object, but then hit another weird issue with an illegal classfile dependency between EndpointsWatch and its companion object.

Sooo... ¯\\\_(ツ)\_/¯

**Comment by adleong** [comment]
With this change getting the class name no longer produces an excpetion:

```
scala> io.buoyant.k8s.v1.Added.getClass.getSimpleName
res2: String = Added$
```

**Comment by olix0r** [comment]
lgtm! this definitely deserves an entry in CHANGES. maybe even with a '***BUGFIX***' ;)

**Comment by gtcampbell** [comment]
:star: thanks for the explanation! Was/would it be possible to reproduce the problem in a test?
