### PR TITLE
switch /admin/metrics usage from GET to POST

### LINKED ISSUE #265: Fix request URI too long errors in dashboard data requests
When running the calcluator app (4 routers with 1 service each, plus I added 2 more adder services for a total of 6 clients), I get JS errors: `Failed to load resource: the server responded with a status of 414 (Request-URI Too Long)`

```
jquery.min.js:4 GET http://localhost:9990/admin/metrics?m=&m=&m=jvm%2Fuptime&m=jvm%2Fthread%2Fc…ractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fsuccess&m=&_=1460404668432 414 (Request-URI Too Long)k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4update @ metrics_collector.js:48
jquery.min.js:4 GET http://localhost:9990/admin/metrics?m=&m=&m=jvm%2Fuptime&m=jvm%2Fthread%2Fc…ractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fsuccess&m=&_=1460404668434 414 (Request-URI Too Long)k.cors.a.crossDomain.send @ jquery.min.js:4n.extend.ajax @ jquery.min.js:4update @ metrics_collector.js:48
```

This is the request the dashboard is making:
```
curl 'http://localhost:9990/admin/metrics?m=&m=&m=jvm%2Fuptime&m=jvm%2Fthread%2Fcount&m=jvm%2Fmem%2Fcurrent%2Fused&m=jvm%2Fgc%2Fmsec&m=rt%2Fdivider%2Fsrv%2F0.0.0.0%2F4117%2Fload&m=rt%2Fmultiplier%2Fsrv%2F0.0.0.0%2F4116%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Fconnections&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Fconnections&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Fconnections&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Fconnections&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fconnections&m=rt%2Fmultiplier%2Fsrv%2F0.0.0.0%2F4116%2Fload&m=rt%2Fadder%2Fsrv%2F0.0.0.0%2F4114%2Fconnections&m=rt%2Fsubtractor%2Fsrv%2F0.0.0.0%2F4115%2Fconnections&m=rt%2Fmultiplier%2Fsrv%2F0.0.0.0%2F4116%2Fconnections&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Fconnections&m=rt%2Fdivider%2Fsrv%2F0.0.0.0%2F4117%2Frequests&m=rt%2Fsubtractor%2Fsrv%2F0.0.0.0%2F4115%2Fload&m=rt%2Fsubtractor%2Fsrv%2F0.0.0.0%2F4115%2Frequests&m=rt%2Fadder%2Fsrv%2F0.0.0.0%2F4114%2Fload&m=rt%2Fdivider%2Fsrv%2F0.0.0.0%2F4117%2Fconnections&m=rt%2Fadder%2Fsrv%2F0.0.0.0%2F4114%2Frequests&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Floadbalancer%2Fload&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Fsuccess&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Fload&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Frequests&m=rt%2Fmultiplier%2Fsrv%2F0.0.0.0%2F4116%2Fsuccess&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Fsuccess&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Fload&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Floadbalancer%2Fload&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Frequests&m=rt%2Fdivider%2Fsrv%2F0.0.0.0%2F4117%2Fsuccess&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fload&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Floadbalancer%2Fload&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fsuccess&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Frequests&m=rt%2Fsubtractor%2Fsrv%2F0.0.0.0%2F4115%2Fsuccess&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Fsuccess&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Fsuccess&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Fload&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Floadbalancer%2Fload&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Floadbalancer%2Fload&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Fsuccess&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Fload&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Floadbalancer%2Fload&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Fload&m=rt%2Fadder%2Fsrv%2F0.0.0.0%2F4114%2Fsuccess&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Frequests&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Fconnections&m=rt%2Fmultiplier%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9092%2Fsuccess&m=&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Fconnections&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9090%2Fsuccess&m=&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Fconnections&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9089%2Fsuccess&m=&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Frequests&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Fconnections&m=rt%2Fadder%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9088%2Fsuccess&m=&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Frequests&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Fconnections&m=rt%2Fdivider%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9093%2Fsuccess&m=&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Frequests&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fconnections&m=rt%2Fsubtractor%2Fdst%2Fid%2F%24%2Finet%2F127.1%2F9091%2Fsuccess&m=&_=1460404668776' -H 'Pragma: no-cache' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'l5d-sample: 0.9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Referer: http://localhost:9990/dashboard' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: buoyant-oauth-nonce=gKJGNDnGGR; _ga=GA1.1.1664851384.1453846975' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
```

We should diagnose this.
Make sure we're not duplicating any requests.

Part of #183

### PR DESCRIPTION
**Pull request by siggy**
setting a request body on POST, allowing more metrics params than a GET
query string

fixes #265

### CODE REVIEW

**Comment by esbie** [comment]
:star: we could also read the body of the GET. It doesn't follow the http spec exactly, but the intent might be more clear than a POST

**Comment by siggy** [comment]
agree using GET requests makes more sense in some ways. i considered doing this, then came across this:
http://stackoverflow.com/questions/978061/http-get-with-request-body

so, rather than modifying the existing API for GETs, i opted to only change how POSTS are handled.

**Comment by rmars** [comment]
⭐ ♐

File: linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala [hunk 1]
```diff
@@ -14,6 +14,7 @@ class BuoyantMainTest extends TwitterServer {
   def main() {}
 }
 
+// TODO: these tests are not getting run
```
Comment (olix0r) [inline linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala]: ???

File: admin/src/main/scala/io/buoyant/admin/MetricsQueryHandler.scala [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+import com.twitter.finagle.http.{Method, Request, Response}
+import com.twitter.server.handler.MetricQueryHandler
+import com.twitter.util.Future
+
+class MetricsQueryHandler extends MetricQueryHandler {
+  override def apply(req: Request): Future[Response] = {
+    if (req.method == Method.Post) {
+      req.uri = s"/admin/metrics?${req.contentString}"
+    }
+    super.apply(req)
```
Comment (olix0r) [inline admin/src/main/scala/io/buoyant/admin/MetricsQueryHandler.scala]: whoa! i never would have thought of this. crafty!

File: linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala (hunk 1 above)
Comment (olix0r) [inline linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala]:
```
:; ./sbt linkerd-admin/test
...
[info] LinkerdAdminTest:
[info] - serves buoyant admin at /
[info] - serves buoyant static files at /files
[info] - serves 404 for a non-existent route
[info] - serves twitter-server admin at /admin
[info] - serves twitter-server static files at /admin/files
[info] - serves /admin/metrics.json
...
```

Comment (siggy) [inline linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala]: more specifically, code inside the `new BuoyantMainTest {` clause is not getting run. i tried to piece together when in git history this could have happened, may have been in a previous repo.

Comment (olix0r) [inline linkerd/admin/src/test/scala/io/buoyant/linkerd/admin/LinkerdAdminTest.scala]: oh, yeah, i see.  nothing actually calls main

**Comment by olix0r** [comment]
:star:
