### PR TITLE
Disable failure accrual for zipkin client

### LINKED ISSUE #510: reconfigure zipkin-tracer client to gracefully degrade under load
### Problem
At 5ms latency, we're observing the zipkin-tracer client max out at 250qps (500 traces/s at 2 spans/request). Above 250qps, zipkin-tracer degrades significantly with high `TooManyWaitersException` counts.

In a higher-latency test (38ms), doubling trace/s from 100 to 200 caused successful throughput to drop from 100 to 7 traces/s.

Stats from the degraded case:
```json
{
"clnt/zipkin-tracer/failures": 61233,
"clnt/zipkin-tracer/failures/com.twitter.util.TimeoutException": 59664,
"clnt/zipkin-tracer/success": 2486,
"clnt/zipkin-tracer/requests": 63719,
"clnt/zipkin-tracer/connect_latency_ms.p50": 38,
"clnt/zipkin-tracer/request_latency_ms.p50": 9,
"clnt/zipkin-tracer/service_creation/failures": 2471062,
"clnt/zipkin-tracer/tries/requests": 2534781,
"clnt/zipkin-tracer/tries/failures/com.twitter.finagle.TooManyWaitersException": 2255617,
"clnt/zipkin-tracer/requests": 63719,
}
```

### Solution

Reconfigure the zipkin-tracer client to gracefully degrade. It is currently hardcoded in finagle:

https://github.com/twitter/finagle/blob/develop/finagle-zipkin/src/main/scala/com/twitter/finagle/zipkin/thrift/ScribeRawZipkinTracer.scala#L25

```scala
    val transport = ClientBuilder()
      .name(name)
      .hosts(new InetSocketAddress(scribeHost, scribePort))
      .codec(ThriftClientFramedCodec())
      .reportTo(ClientStatsReceiver)
      .hostConnectionLimit(5)
      // using an arbitrary, but bounded number of waiters to avoid memory leaks
      .hostConnectionMaxWaiters(250)
      // somewhat arbitrary, but bounded timeouts
      .timeout(1.second)
      .daemon(true)
      .build()
```

@gtcampbell has a starting point at: https://github.com/BuoyantIO/linkerd/commit/c93c3cf54e95e89593db64fcaf3c3946a945e3cf

### PR DESCRIPTION
**Pull request by adleong**
fixes #510 

* disable failure accrual
* disable fail fast
* reduce timeout to 100ms

These changes allow linkerd to continue to saturate the zipkin client's connections, even when total sampled RPS is much higher than what can be sent.

### CODE REVIEW

File: linkerd/tracer/zipkin/src/main/scala/io/buoyant/linkerd/tracer/ZipkinTracerInitializer.scala [hunk 1]
```diff
@@ -20,15 +28,52 @@ case class ZipkinConfig(
...
+        .reportTo(ClientStatsReceiver)
+        .hostConnectionLimit(5)
+        // using an arbitrary, but bounded number of waiters to avoid memory leaks
+        .hostConnectionMaxWaiters(250)
+        // somewhat arbitrary, but bounded timeouts
+        .timeout(100.millis)
+        .daemon(true)
+        .noFailureAccrual
+        .failFast(false)
+        .build()
```
Comment (gtcampbell) [inline linkerd/tracer/zipkin/src/main/scala/io/buoyant/linkerd/tracer/ZipkinTracerInitializer.scala]: it might be good to add comments indicating which settings differ from the default values from ZipkinTracer

Comment (gtcampbell) [inline linkerd/tracer/zipkin/src/main/scala/io/buoyant/linkerd/tracer/ZipkinTracerInitializer.scala]: (and also add a comment noting where this was copied from)

**Comment by gtcampbell** [comment]
:star: my comments are non-blocking since they're documentation-only; it might be good to add some information to this PR or the code indicating how these changes impacted performance. (I have some decent guesses given our discussions of the last few days, but not hard numbers, obviously).

**Comment by gtcampbell** [comment]
:star: thanks!

**Comment by siggy** [comment]
⭐ 👍 thanks!

**Comment by olix0r** [comment]
lgtm
